### ISSUE TITLE
fasta_read() return type is bool, not FASTA_rec_t*

### ISSUE THREAD

**Issue by anadon** [dkopecek/libfasta#1]
I'm trying to compile your project here, but there is the most bizarre issue that I though I should message you before going down any rabbit holes.  It appears that at compile time, fasta_read() returns type bool, despite the declaration in fasta.h being of type FASTA_rec_t*.  Do you have an idea why this might be?

g++ -g -Wall -pipe -lfasta -lpthread --std=gnu++0x  main.cpp -o mummer
main.cpp: In function ‘globalArgs parseArgs(int, char*_)’:
main.cpp:229:25: error: cannot convert ‘bool’ to ‘FASTA_rec_t_’ in assignment
    while(tmpFastaRecord = fasta_read(inFile, NULL, 0, NULL) != NULL){

**Comment by dkopecek** [comment]
Hello! Could you please provide the complete source of main.cpp? Aren't you missing parentheses in your while condition? i.e.:

while(`(`tmpFastaRecord = fasta_read(inFile, NULL, 0, NULL)`)` != NULL) {

**Comment by anadon** [comment]
The problem was between the keyboard and the chair all along.  How many years have I been coding and I still miss things like that?
